name: Tamanduá
favicon: null
layout_spectrum: 0.7036679200828075
typography_spectrum: 0.10997022595256567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6797179272398353
  lightness: 0.23916829330846667
  saturation: 0.4745854055508971
  rhythmicContrast: 0.04615607741288841
purpose: []
